[meta]
name = "RESTAPI-MCDR"
author = [{ "github" = "Mooling0602" }]
maintainers = []
description = "A RESTful API for MCDReforged."
main-branch = "main"
license = "GPL-3.0"

[platform]
remote-hoster = [{ "github" = "https://github.com" }]
